version: '3'

services:
  json_schematize:
    command: tail -f /dev/null
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/gem
      - ..:/local
      - bundle-cache:/usr/local/bundle:delegated
    environment:
      REDIS_URL: redis://redis
    links:
      - redis
  redis:
    image: redis
    expose:
      - 6379
volumes:
  bundle-cache:
